name: Auto Comment

on:
  issues:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment for bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you. We will fix it"

      - name: Comment for feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you, we will consider to include this feature."

      - name: Comment for no label
        if: ${{ !contains(github.event.issue.labels.*.name, 'bug') && !contains(github.event.issue.labels.*.name, 'feature') }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you for your contribution!"
