name: Automated Comment Bot
on:
  issues:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it'
            })
      - name: Comment on feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature.'
            })
      - name: Comment when no label
        if: github.event.issue.labels == null || join(github.event.issue.labels.*.name) == ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for your contribution!'
            })
