name: Automated Comment Bot

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you. We will fix it"
      - name: Comment on feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you, we will consider to include this feature."
      - name: Comment without label
        if: join(github.event.issue.labels.*.name) == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thank you for your contribution!"
