name: Issue Comment Bot
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.issue.labels.map(l => l.name);
            let msg = "Thank you for your contribution!";
            if (labels.includes("bug")) {
              msg = "Thank you. We will fix it";
            } else if (labels.includes("feature")) {
              msg = "Thank you, we will consider to include this feature.";
            }
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
