name: Auto Comment
on:
  issues:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it'
            })
      - name: Check feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature.'
            })
      - name: Check no label
        if: toJSON(github.event.issue.labels) == '[]'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for your contribution!'
            })
